name: E2E test

on:
  pull_request:
    types: [labeled]

jobs:
  e2e-test:
    if: contains(github.event.pull_request.labels.*.name, 'E2E')
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install node version 12
        uses: actions/setup-node@v1
        with:
          node-version: "12"

      - name: Prepare .env file
        env:
          FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}
          FIREBASE_AUTH_DOMAIN: ${{ secrets.FIREBASE_AUTH_DOMAIN }}
          FIREBASE_DATABASE_URL: ${{ secrets.FIREBASE_DATABASE_URL }}
          FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
          FIREBASE_STORAGE_BUCKET: ${{ secrets.FIREBASE_STORAGE_BUCKET }}
          FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}
          FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID }}
          FIREBASE_MEASUREMENT_ID: ${{ secrets.FIREBASE_MEASUREMENT_ID }}
        run: |
          line1="FIREBASE_API_KEY=${FIREBASE_API_KEY}"
          line2="FIREBASE_AUTH_DOMAIN=${FIREBASE_AUTH_DOMAIN}"
          line3="FIREBASE_DATABASE_URL=${FIREBASE_DATABASE_URL}"
          line4="FIREBASE_PROJECT_ID=${FIREBASE_PROJECT_ID}"
          line5="FIREBASE_STORAGE_BUCKET=${FIREBASE_STORAGE_BUCKET}"
          line6="FIREBASE_MESSAGING_SENDER_ID=${FIREBASE_MESSAGING_SENDER_ID}"
          line7="FIREBASE_APP_ID=${FIREBASE_APP_ID}"
          line8="FIREBASE_MEASUREMENT_ID=${FIREBASE_MEASUREMENT_ID}"
          printf "${line1}\n${line2}\n${line3}\n${line4}\n${line5}\n${line6}\n${line7}\n${line8}\n" > .env

      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: "/home/runner/.cache/firebase/emulators"
          key: firebase-emulator

      - name: Install dependencies
        run: yarn

      - name: Install firebase-cli
        run: yarn global add firebase-tools

      - name: Serve site at localhost
        run: (yarn dev&)

      - name: Serve Firestore as backend
        uses: w9jds/firebase-action@master
        with:
          args: emulators:start --only firestore
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_CLI_TOKEN }}

      - name: Run E2E test
        uses: cypress-io/github-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          install: false
          wait-on: "http://localhost:5000/firestore"
          wait-on-timeout: 300
          browser: ${{ env.BROWSER }}
          headless: true

      - run: curl http://localhost:5000

      - name: Remove E2E Label
        uses: actions-ecosystem/action-remove-labels@v1
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          labels: |
            E2E
