name: E2E test

on:
  pull_request:
    types: [labeled]

jobs:
  e2e-test:
    if: contains(github.event.pull_request.labels.*.name, 'E2E')
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install node version 12
        uses: actions/setup-node@v1
        with:
          node-version: "12"

      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: |
            "**/node_modules"
            "**/.config/yarn/global"
            "/home/runner/.cache/Cypress/6.0.0/Cypress/Cypress"
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Install dependencies
        run: |
          yarn
          yarn global add firebase-tools

      - name: Serve site at localhost
        run: (yarn dev&)

      - name: Wait for localhost to be served
        run: |
          until [ -n "$(curl --silent http://localhost:3000 | grep 'logo')" ]; do
            printf '.'
            sleep 5
          done

      - name: Run E2E with cypress
        run: yarn e2e:onetime

      - name: Remove E2E Label
        uses: actions-ecosystem/action-remove-labels@v1
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          labels: |
            E2E
